// Generated by scripts/gen-db-types.ts from supabase/migrations. Do not edit by hand.
// Regenerate with: npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      ai_usage: {
        Row: {
          id: number;
          business_id: string;
          conversation_id: string | null;
          model: string;
          input_tokens: number;
          output_tokens: number;
          tool_calls: number;
          created_at: string;
        };
        Insert: {
          id?: number;
          business_id: string;
          conversation_id?: string | null;
          model: string;
          input_tokens?: number;
          output_tokens?: number;
          tool_calls?: number;
          created_at?: string;
        };
        Update: {
          id?: number;
          business_id?: string;
          conversation_id?: string | null;
          model?: string;
          input_tokens?: number;
          output_tokens?: number;
          tool_calls?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_usage_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      appointments: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string;
          service_id: string;
          staff_id: string;
          conversation_id: string | null;
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          status: string;
          source: string;
          price: number | null;
          notes: string;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id: string;
          service_id: string;
          staff_id: string;
          conversation_id?: string | null;
          starts_at: string;
          ends_at: string;
          blocked_until: string;
          status?: string;
          source?: string;
          price?: number | null;
          notes?: string;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string;
          service_id?: string;
          staff_id?: string;
          conversation_id?: string | null;
          starts_at?: string;
          ends_at?: string;
          blocked_until?: string;
          status?: string;
          source?: string;
          price?: number | null;
          notes?: string;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "appointments_business_id_conversation_id_fkey";
            columns: ["business_id","conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["business_id","id"];
          },
          {
            foreignKeyName: "appointments_business_id_customer_id_fkey";
            columns: ["business_id","customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["business_id","id"];
          },
          {
            foreignKeyName: "appointments_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "appointments_business_id_service_id_fkey";
            columns: ["business_id","service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["business_id","id"];
          },
          {
            foreignKeyName: "appointments_business_id_staff_id_fkey";
            columns: ["business_id","staff_id"];
            isOneToOne: false;
            referencedRelation: "staff";
            referencedColumns: ["business_id","id"];
          },
        ];
      };
      assistant_settings: {
        Row: {
          business_id: string;
          enabled: boolean;
          assistant_name: string;
          tone: string;
          languages: string[];
          greeting: string;
          instructions: string;
          updated_at: string;
        };
        Insert: {
          business_id: string;
          enabled?: boolean;
          assistant_name?: string;
          tone?: string;
          languages?: string[];
          greeting?: string;
          instructions?: string;
          updated_at?: string;
        };
        Update: {
          business_id?: string;
          enabled?: boolean;
          assistant_name?: string;
          tone?: string;
          languages?: string[];
          greeting?: string;
          instructions?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assistant_settings_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: true;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      booking_settings: {
        Row: {
          business_id: string;
          slot_interval_min: number;
          min_notice_min: number;
          max_advance_days: number;
          buffer_min: number;
          cancellation_notice_hours: number;
          auto_confirm: boolean;
          updated_at: string;
        };
        Insert: {
          business_id: string;
          slot_interval_min?: number;
          min_notice_min?: number;
          max_advance_days?: number;
          buffer_min?: number;
          cancellation_notice_hours?: number;
          auto_confirm?: boolean;
          updated_at?: string;
        };
        Update: {
          business_id?: string;
          slot_interval_min?: number;
          min_notice_min?: number;
          max_advance_days?: number;
          buffer_min?: number;
          cancellation_notice_hours?: number;
          auto_confirm?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "booking_settings_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: true;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      business_members: {
        Row: {
          business_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          business_id: string;
          user_id: string;
          role?: string;
          created_at?: string;
        };
        Update: {
          business_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "business_members_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      businesses: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: string;
          description: string;
          timezone: string;
          currency: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          maps_url: string | null;
          status: string;
          plan: string;
          trial_ends_at: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category?: string;
          description?: string;
          timezone?: string;
          currency?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          maps_url?: string | null;
          status?: string;
          plan?: string;
          trial_ends_at?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: string;
          description?: string;
          timezone?: string;
          currency?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          maps_url?: string | null;
          status?: string;
          plan?: string;
          trial_ends_at?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      conversations: {
        Row: {
          id: string;
          business_id: string;
          customer_id: string;
          channel: string;
          external_id: string;
          mode: string;
          status: string;
          needs_attention: boolean;
          handover_reason: string | null;
          language: string | null;
          last_message_at: string;
          last_message_preview: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          customer_id: string;
          channel: string;
          external_id: string;
          mode?: string;
          status?: string;
          needs_attention?: boolean;
          handover_reason?: string | null;
          language?: string | null;
          last_message_at?: string;
          last_message_preview?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          customer_id?: string;
          channel?: string;
          external_id?: string;
          mode?: string;
          status?: string;
          needs_attention?: boolean;
          handover_reason?: string | null;
          language?: string | null;
          last_message_at?: string;
          last_message_preview?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversations_business_id_customer_id_fkey";
            columns: ["business_id","customer_id"];
            isOneToOne: false;
            referencedRelation: "customers";
            referencedColumns: ["business_id","id"];
          },
          {
            foreignKeyName: "conversations_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      customers: {
        Row: {
          id: string;
          business_id: string;
          name: string | null;
          phone: string | null;
          email: string | null;
          language: string | null;
          notes: string;
          source: string;
          stage: string;
          last_contact_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string | null;
          notes?: string;
          source?: string;
          stage?: string;
          last_contact_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string | null;
          notes?: string;
          source?: string;
          stage?: string;
          last_contact_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "customers_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      faqs: {
        Row: {
          id: string;
          business_id: string;
          question: string;
          answer: string;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          question: string;
          answer: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          question?: string;
          answer?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "faqs_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      messages: {
        Row: {
          id: string;
          business_id: string;
          conversation_id: string;
          role: string;
          content: string;
          actions: Json;
          external_id: string | null;
          delivery_status: string | null;
          sent_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          conversation_id: string;
          role: string;
          content: string;
          actions?: Json;
          external_id?: string | null;
          delivery_status?: string | null;
          sent_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          conversation_id?: string;
          role?: string;
          content?: string;
          actions?: Json;
          external_id?: string | null;
          delivery_status?: string | null;
          sent_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_business_id_conversation_id_fkey";
            columns: ["business_id","conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["business_id","id"];
          },
        ];
      };
      platform_admins: {
        Row: {
          user_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      platform_settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string;
          locale: string;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string;
          locale?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          locale?: string;
          created_at?: string;
        };
        Relationships: [
        ];
      };
      rate_limits: {
        Row: {
          key: string;
          window_start: string;
          hits: number;
        };
        Insert: {
          key: string;
          window_start: string;
          hits: number;
        };
        Update: {
          key?: string;
          window_start?: string;
          hits?: number;
        };
        Relationships: [
        ];
      };
      services: {
        Row: {
          id: string;
          business_id: string;
          name: Json;
          description: Json;
          duration_min: number;
          price: number | null;
          price_is_from: boolean;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: Json;
          description?: Json;
          duration_min: number;
          price?: number | null;
          price_is_from?: boolean;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: Json;
          description?: Json;
          duration_min?: number;
          price?: number | null;
          price_is_from?: boolean;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "services_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      staff: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          title: string;
          color: string;
          active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          title?: string;
          color?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          title?: string;
          color?: string;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "staff_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      staff_hours: {
        Row: {
          id: string;
          business_id: string;
          staff_id: string;
          weekday: number;
          starts_at: string;
          ends_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          staff_id: string;
          weekday: number;
          starts_at: string;
          ends_at: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          staff_id?: string;
          weekday?: number;
          starts_at?: string;
          ends_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "staff_hours_business_id_staff_id_fkey";
            columns: ["business_id","staff_id"];
            isOneToOne: false;
            referencedRelation: "staff";
            referencedColumns: ["business_id","id"];
          },
        ];
      };
      staff_services: {
        Row: {
          business_id: string;
          staff_id: string;
          service_id: string;
        };
        Insert: {
          business_id: string;
          staff_id: string;
          service_id: string;
        };
        Update: {
          business_id?: string;
          staff_id?: string;
          service_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "staff_services_business_id_service_id_fkey";
            columns: ["business_id","service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["business_id","id"];
          },
          {
            foreignKeyName: "staff_services_business_id_staff_id_fkey";
            columns: ["business_id","staff_id"];
            isOneToOne: false;
            referencedRelation: "staff";
            referencedColumns: ["business_id","id"];
          },
        ];
      };
      time_off: {
        Row: {
          id: string;
          business_id: string;
          staff_id: string | null;
          starts_at: string;
          ends_at: string;
          reason: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          staff_id?: string | null;
          starts_at: string;
          ends_at: string;
          reason?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          staff_id?: string | null;
          starts_at?: string;
          ends_at?: string;
          reason?: string;
        };
        Relationships: [
          {
            foreignKeyName: "time_off_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "time_off_business_id_staff_id_fkey";
            columns: ["business_id","staff_id"];
            isOneToOne: false;
            referencedRelation: "staff";
            referencedColumns: ["business_id","id"];
          },
        ];
      };
      whatsapp_accounts: {
        Row: {
          business_id: string;
          phone_number_id: string;
          waba_id: string;
          display_phone_number: string;
          verified_name: string;
          status: string;
          connected_at: string;
        };
        Insert: {
          business_id: string;
          phone_number_id: string;
          waba_id: string;
          display_phone_number?: string;
          verified_name?: string;
          status?: string;
          connected_at?: string;
        };
        Update: {
          business_id?: string;
          phone_number_id?: string;
          waba_id?: string;
          display_phone_number?: string;
          verified_name?: string;
          status?: string;
          connected_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "whatsapp_accounts_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: true;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
      whatsapp_credentials: {
        Row: {
          business_id: string;
          access_token_encrypted: string;
          updated_at: string;
        };
        Insert: {
          business_id: string;
          access_token_encrypted: string;
          updated_at?: string;
        };
        Update: {
          business_id?: string;
          access_token_encrypted?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "whatsapp_credentials_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: true;
            referencedRelation: "whatsapp_accounts";
            referencedColumns: ["business_id"];
          },
        ];
      };
      working_hours: {
        Row: {
          id: string;
          business_id: string;
          weekday: number;
          opens_at: string;
          closes_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          weekday: number;
          opens_at: string;
          closes_at: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          weekday?: number;
          opens_at?: string;
          closes_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "working_hours_business_id_fkey";
            columns: ["business_id"];
            isOneToOne: false;
            referencedRelation: "businesses";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      create_business: { Args: { p_name: string; p_slug: string; p_category: string; p_timezone: string; p_currency: string; p_languages: string[] }; Returns: string };
      hit_rate_limit: { Args: { p_key: string; p_limit: number; p_window_seconds: number }; Returns: boolean };
      is_platform_admin: { Args: never; Returns: boolean };
      is_valid_timezone: { Args: { tz: string }; Returns: boolean };
      member_business_ids: { Args: { p_roles?: string[] }; Returns: string[] };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
