/**
 * Generates src/lib/supabase/database.types.ts from the SQL migrations.
 *
 * It applies every migration to an in-memory Postgres (PGlite) and introspects
 * the result, emitting the same shape as `supabase gen types typescript`.
 * No Docker, network or Supabase account needed:  npm run db:types
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createTestDb } from "../supabase/tests/harness";

type Column = {
  table_name: string;
  column_name: string;
  udt_name: string;
  data_type: string;
  is_nullable: "YES" | "NO";
  column_default: string | null;
  is_identity: "YES" | "NO";
};
type ForeignKey = {
  name: string;
  table_name: string;
  columns: string[];
  referenced_table: string;
  referenced_columns: string[];
  one_to_one: boolean;
};
type Fn = { name: string; arg_names: string[] | null; arg_types: string[]; arg_defaults: number; returns: string; returns_set: boolean };

const SCALARS: Record<string, string> = {
  uuid: "string",
  text: "string",
  varchar: "string",
  citext: "string",
  time: "string",
  date: "string",
  timestamptz: "string",
  timestamp: "string",
  tstzrange: "unknown",
  int2: "number",
  int4: "number",
  int8: "number",
  numeric: "number",
  float4: "number",
  float8: "number",
  bool: "boolean",
  json: "Json",
  jsonb: "Json",
  void: "undefined",
};

const tsType = (udt: string): string =>
  udt.startsWith("_") ? `${tsType(udt.slice(1))}[]` : (SCALARS[udt] ?? "unknown");

const key = (name: string) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : JSON.stringify(name));

async function main() {
  const db = await createTestDb();

  const columns = (
    await db.query<Column>(`
      select c.table_name, c.column_name, c.udt_name, c.data_type, c.is_nullable, c.column_default, c.is_identity
        from information_schema.columns c
        join information_schema.tables t on t.table_schema = c.table_schema and t.table_name = c.table_name
       where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
       order by c.table_name, c.ordinal_position`)
  ).rows;

  const foreignKeys = (
    await db.query<ForeignKey>(`
      select con.conname as name,
             rel.relname as table_name,
             array(select att.attname from unnest(con.conkey) with ordinality k(n, i)
                     join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k.n order by k.i) as columns,
             ref.relname as referenced_table,
             array(select att.attname from unnest(con.confkey) with ordinality k(n, i)
                     join pg_attribute att on att.attrelid = con.confrelid and att.attnum = k.n order by k.i) as referenced_columns,
             exists (
               select 1 from pg_constraint u
                where u.conrelid = con.conrelid and u.contype in ('p', 'u')
                  and (select array_agg(x order by x) from unnest(u.conkey) x)
                    = (select array_agg(x order by x) from unnest(con.conkey) x)
             ) as one_to_one
        from pg_constraint con
        join pg_class rel on rel.oid = con.conrelid
        join pg_class ref on ref.oid = con.confrelid
        join pg_namespace ns on ns.oid = rel.relnamespace
        join pg_namespace refns on refns.oid = ref.relnamespace
       where con.contype = 'f' and ns.nspname = 'public' and refns.nspname = 'public'
       order by rel.relname, con.conname`)
  ).rows;

  const functions = (
    await db.query<Fn>(`
      select p.proname as name,
             p.proargnames as arg_names,
             array(select format_type(t, null) from unnest(p.proargtypes) t) as arg_types,
             p.pronargdefaults as arg_defaults,
             (select typname from pg_type where oid = p.prorettype) as returns,
             p.proretset as returns_set
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public'
         and p.prorettype <> 'trigger'::regtype
         and p.proname not in ('set_updated_at')
       order by p.proname`)
  ).rows;

  const tables = [...new Set(columns.map((c) => c.table_name))];
  const out: string[] = [];

  out.push(
    "// Generated by scripts/gen-db-types.ts from supabase/migrations. Do not edit by hand.",
    "// Regenerate with: npm run db:types",
    "",
    "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
    "",
    "export type Database = {",
    "  public: {",
    "    Tables: {",
  );

  for (const table of tables) {
    const cols = columns.filter((c) => c.table_name === table);
    const field = (c: Column, mode: "Row" | "Insert" | "Update") => {
      const type = tsType(c.udt_name) + (c.is_nullable === "YES" ? " | null" : "");
      const optional =
        mode === "Update" || (mode === "Insert" && (c.is_nullable === "YES" || c.column_default !== null || c.is_identity === "YES"));
      return `          ${key(c.column_name)}${optional ? "?" : ""}: ${type};`;
    };
    out.push(`      ${key(table)}: {`);
    for (const mode of ["Row", "Insert", "Update"] as const) {
      out.push(`        ${mode}: {`, ...cols.map((c) => field(c, mode)), "        };");
    }
    const rels = foreignKeys.filter((f) => f.table_name === table);
    out.push("        Relationships: [");
    for (const f of rels) {
      out.push(
        "          {",
        `            foreignKeyName: ${JSON.stringify(f.name)};`,
        `            columns: ${JSON.stringify(f.columns)};`,
        `            isOneToOne: ${f.one_to_one};`,
        `            referencedRelation: ${JSON.stringify(f.referenced_table)};`,
        `            referencedColumns: ${JSON.stringify(f.referenced_columns)};`,
        "          },",
      );
    }
    out.push("        ];", "      };");
  }

  out.push("    };", "    Views: { [_ in never]: never };", "    Functions: {");
  for (const fn of functions) {
    const names = fn.arg_names ?? [];
    const firstDefault = fn.arg_types.length - fn.arg_defaults;
    const args = fn.arg_types.map((t, i) => {
      const udt = t.endsWith("[]") ? `_${t.slice(0, -2)}` : t;
      const normalized = { "text": "text", "uuid": "uuid", "integer": "int4", "boolean": "bool", "_text": "_text" }[udt] ?? udt;
      return `${key(names[i] ?? `arg${i}`)}${i >= firstDefault ? "?" : ""}: ${tsType(normalized)}`;
    });
    const returns = tsType(fn.returns) + (fn.returns_set ? "[]" : "");
    out.push(`      ${key(fn.name)}: { Args: ${args.length ? `{ ${args.join("; ")} }` : "never"}; Returns: ${returns} };`);
  }
  out.push(
    "    };",
    "    Enums: { [_ in never]: never };",
    "    CompositeTypes: { [_ in never]: never };",
    "  };",
    "};",
    "",
    'type PublicSchema = Database["public"];',
    'export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];',
    'export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];',
    'export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];',
    "",
  );

  const target = join(import.meta.dirname, "..", "src", "lib", "supabase", "database.types.ts");
  writeFileSync(target, out.join("\n"));
  console.log(`Wrote ${tables.length} tables and ${functions.length} functions to ${target}`);
  await db.close();
}

await main();
